name: GitHub Space Shooter

on:
  workflow_dispatch:

jobs:
  space-shooter:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Space Shooter
        uses: czl9707/gh-space-shooter@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
